### ISSUE TITLE
0.7.0 fails to build on macOS 11 (x86_64): `cell.h: error: no type named 'floating_point' in namespace 'std'`

### ISSUE THREAD

**Issue by barracuda156** [FEniCS/basix#752]
```
  /usr/bin/clang++ -Dbasix_EXPORTS -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_basix/basix/work/build -I/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_basix/basix/work/basix-0.7.0/cpp -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -mmacosx-version-min=11.0 -fPIC -std=c++20 -MD -MT CMakeFiles/basix.dir/basix/cell.cpp.o -MF CMakeFiles/basix.dir/basix/cell.cpp.o.d -o CMakeFiles/basix.dir/basix/cell.cpp.o -c /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_basix/basix/work/basix-0.7.0/cpp/basix/cell.cpp
  In file included from /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_basix/basix/work/basix-0.7.0/cpp/basix/dof-transformations.cpp:5:
  In file included from /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_basix/basix/work/basix-0.7.0/cpp/basix/dof-transformations.h:7:
  In file included from /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_basix/basix/work/basix-0.7.0/cpp/basix/cell.cpp:5:
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_basix/basix/work/basix-0.7.0/cpp/basix/cell.h:37:16: error: no type named 'floating_point' in namespace 'std'
  template <std::floating_point T>
            ~~~~~^
  /opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_science_basix/basix/work/basix-0.7.0/cpp/basix/cell.h:38:23: error: template argument for template type parameter must be a type
  std::pair<std::vector<T>, std::array<std::size_t, 2>>
```
Full log here: https://github.com/macports/macports-ports/actions/runs/7068889534/job/19243969459?pr=21632

Locally builds fine on 14.1.2 on aarch64. I have nothing to test an Intel built on.

**Comment by jhale** [comment]
Correction: macos-12 only, but that should be updated to include macos-13.

**Comment by barracuda156** [comment]
@jhale Ok, let me see if LLVM clang-17 works.
