### ISSUE TITLE
SobolevSpace error

### ISSUE THREAD

**Issue by alirajabi87** [FEniCS/basix#604]
Hi,

I have a problem with importing SobolevSpace in my code.

The error is:

AttributeError: module 'basix' has no attribute 'SobolevSpace'

I would appreciate it if someone can help me.

**Comment by mscroggs** [comment]
Are you using the latest version of Basix?

**Comment by alirajabi87** [comment]
Hi Matthew,

Thanks for the reply.

My current version of basix is **0.5.1**. 

I also checked with **0.5.0**. Both of them same error.

_AttributeError: module 'basix' has no attribute 'sobolev_space'._

I am using my Mac M1 right now but I also tried to install Dolfinx on the CentOS Linux cluster and during the installation, I encountered the same error.

**Comment by mscroggs** [comment]
Are you building DOLFINx from the latest main branch? If so, this requires changes that have been made in Basix since the last version release.

Alternatively, if you checkout the v0.5.1 tag of DOLFINx, you should be able to build using the 0.5.1 version of Basix
